AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB tables for Admin Tool
Transform: AWS::Serverless-2016-10-31

Parameters:
  DeletionProtection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /self-service/config/deletion-protection-enabled
  ExportNamePrefix:
    Type: String
    Default: self-service
    AllowedPattern: ^.*[^-]$
    Description: Prefix to use when importing or exporting values from other application stacks

Conditions:
  DeletionProtectionEnabled: !Equals [ !Ref DeletionProtection, ACTIVE ]

Resources:
  DataTable:
    # checkov:skip=CKV_AWS_28: "Ensure Dynamodb point in time recovery (backup) is enabled"
    # checkov:skip=CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK"
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: !If [ DeletionProtectionEnabled, true, false ]
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SessionsTable:
    # https://github.com/ca98am79/connect-dynamodb#options
    # checkov:skip=CKV_AWS_28: "Ensure Dynamodb point in time recovery (backup) is enabled"
    # checkov:skip=CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK"
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true

Outputs:
  DataTableName:
    Value: !Ref DataTable
    Export:
      Name: !Sub ${ExportNamePrefix}-DataTableName
  SessionsTableName:
    Value: !Ref SessionsTable
    Export:
      Name: !Sub ${ExportNamePrefix}-SessionsTableName
  SessionsTableArn:
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub ${ExportNamePrefix}-SessionsTableArn
