AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB tables for Admin Tool

Parameters:
  DeletionProtection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /self-service/config/deletion-protection-enabled
  DeploymentName:
    Type: String
    MaxLength: 28
    AllowedPattern: ^.*[^-]$
    Default: self-service
    Description: A unique prefix to identify the deployment; used when importing or exporting values from related stacks

Conditions:
  DeletionProtectionEnabled: !Equals [ !Ref DeletionProtection, ACTIVE ]

Resources:
  DataTable:
    # checkov:skip=CKV_AWS_28:Ensure Dynamodb point in time recovery (backup) is enabled
    # checkov:skip=CKV_AWS_119:Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${DeploymentName}-data
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: !If [ DeletionProtectionEnabled, true, false ]
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: BackupFrequency
          Value: Daily

  SessionsTable:
    # https://github.com/ca98am79/connect-dynamodb#options
    # checkov:skip=CKV_AWS_28:Ensure Dynamodb point in time recovery (backup) is enabled
    # checkov:skip=CKV_AWS_119:Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${DeploymentName}-sessions
      DeletionProtectionEnabled: !If [ DeletionProtectionEnabled, true, false ]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true
      SSESpecification:
        SSEEnabled: true


    ## CodeRequestBlockTable ##

  CodeRequestBlockEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS encryption key for CodeRequestBlock DynamoDB table
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: AllowIamManagement
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: AllowDynamodbAccessToEncryptionKey
            Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:dynamodb:table/arn: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*

  CodeRequestBlockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DeploymentName}-Code-Request-Block
      AttributeDefinitions:
        - AttributeName: CodeBlockIdentifier
          AttributeType: S
      KeySchema:
        - AttributeName: CodeBlockIdentifier
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !GetAtt CodeRequestBlockEncryptionKey.Arn
        SSEType: KMS
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  DataTableName:
    Value: !Ref DataTable
    Export:
      Name: !Sub ${DeploymentName}-DynamoDB-DataTableName
  SessionsTableName:
    Value: !Ref SessionsTable
    Export:
      Name: !Sub ${DeploymentName}-DynamoDB-SessionsTableName
  SessionsTableARN:
    Value: !GetAtt SessionsTable.Arn
    Export:
      Name: !Sub ${DeploymentName}-DynamoDB-SessionsTableARN
  CodeRequestBlockTableName:
    Value: !Ref CodeRequestBlockTable
    Export:
      Name: !Sub ${DeploymentName}-CodeRequestBlockTableName
  CodeRequestBlockTableArn:
    Value: !GetAtt CodeRequestBlockTable.Arn
    Export:
      Name: !Sub ${DeploymentName}-CodeRequestBlockTableArn
  CodeRequestBlockTableKmsKeyArn:
    Value: !GetAtt CodeRequestBlockEncryptionKey.Arn
    Export:
      Name: !Sub ${DeploymentName}-CodeRequestBlockEncryptionKeyArn

