# This is dockerfile foe dev enviroment. The only difference is that there is no Dynatrace integration.

FROM node:current-alpine

ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT

WORKDIR /self-service
COPY package*.json ./

WORKDIR /self-service/express
COPY express/package*.json ./
RUN npm ci --include-workspace-root \
    && npm run build && npm ci --omit=dev

COPY express/dist dist
COPY express/stubs stubs
COPY express/resources resources
COPY express/src/views src/views
COPY express/assets/images assets/images

USER node
CMD STUB_API=${STUB_API:-false} npm start

HEALTHCHECK CMD wget --spider http://localhost:$PORT
