AWSTemplateFormatVersion: "2010-09-09"
Description:  frontend WAF
Transform: AWS::LanguageExtensions

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedPattern: development|build|staging|integration|production

Resources:

  FrontendWebAcl:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Description: Web ACL for Frontend API Gateway
      Name: !Sub '${AWS::StackName}-${Environment}-acl'
      DefaultAction:
        Allow: {}

      Rules:
        - Name: CloudFrontRuleWithRateLimit
          Priority: 0
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RuleWithCloudFrontShieldProtectionWebACLMetric
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: 1000

        - Name: AWS-CRS
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: CrossSiteScripting_BODY
                - Name: CrossSiteScripting_COOKIE
                - Name: CrossSiteScripting_QUERYARGUMENTS
                - Name: CrossSiteScripting_URIPATH
                - Name: EC2MetaDataSSRF_BODY
                - Name: EC2MetaDataSSRF_COOKIE
                - Name: EC2MetaDataSSRF_QUERYARGUMENTS
                - Name: EC2MetaDataSSRF_URIPATH
                - Name: GenericLFI_BODY
                - Name: GenericLFI_QUERYARGUMENTS
                - Name: GenericLFI_URIPATH
                - Name: GenericRFI_BODY
                - Name: GenericRFI_QUERYARGUMENTS
                - Name: GenericRFI_URIPATH
                - Name: NoUserAgent_HEADER
                - Name: RestrictedExtensions_QUERYARGUMENTS
                - Name: RestrictedExtensions_URIPATH
                - Name: SizeRestrictions_BODY
                - Name: SizeRestrictions_Cookie_HEADER
                - Name: SizeRestrictions_QUERYSTRING
                - Name: SizeRestrictions_URIPATH
                - Name: UserAgent_BadBots_HEADER
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-aws-crs-metric'

        - Name: Bad-Inputs
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules:
                - Name: ExploitablePaths_URIPATH
                - Name: Host_localhost_HEADER
                - Name: JavaDeserializationRCE_BODY
                - Name: JavaDeserializationRCE_HEADER
                - Name: JavaDeserializationRCE_QUERYSTRING
                - Name: JavaDeserializationRCE_URIPATH
                # - Name: Log4JRCE
                - Name: PROPFIND_METHOD
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-bad-inputs-metric'

        - Name: Anonymous-IpList
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
              ExcludedRules:
                - Name: AnonymousIPList
                - Name: HostingProviderIPList
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-anonymous-iplist-metric'

        - Name: SQLInject-RuleSet
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
              ExcludedRules:
                - Name: SQLiExtendedPatterns_QUERYARGUMENTS
                - Name: SQLi_BODY
                - Name: SQLi_COOKIE
                - Name: SQLi_QUERYARGUMENTS
                - Name: SQLi_URIPATH
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-SQLinjection-ruleset-metric'

        - Name: RateBased-CountIpRule
          Priority: 5
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          Action:
            Count: { }
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-${Environment}-RateBased-CountIp-ruleset-metric"
            SampledRequestsEnabled: true

      Scope: CLOUDFRONT
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${Environment}'
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AWS::StackName}-${Environment}-metric'
