AWSTemplateFormatVersion: "2010-09-09"
Description: Self-service  Main WAF Web ACL
Transform: AWS::LanguageExtensions

Parameters:
  Environment:
    Type: String
    AllowedPattern: development|build|staging|integration|production

Conditions:
  NotDevelopment: !Not [ !Equals [ !Ref Environment, development ] ]

Resources:
  MainWebAcl:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Description: Web ACL for Frontend API Gateway
      Name: !Sub '${AWS::StackName}-${Environment}-acl'
      DefaultAction:
        Allow: {}

      Rules:
        - Name: AWS-CRS
          Priority: 0
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules:
                - Name: CrossSiteScripting_BODY
                - Name: CrossSiteScripting_COOKIE
                - Name: CrossSiteScripting_QUERYARGUMENTS
                - Name: CrossSiteScripting_URIPATH
                - Name: EC2MetaDataSSRF_BODY
                - Name: EC2MetaDataSSRF_COOKIE
                - Name: EC2MetaDataSSRF_QUERYARGUMENTS
                - Name: EC2MetaDataSSRF_URIPATH
                - Name: GenericLFI_BODY
                - Name: GenericLFI_QUERYARGUMENTS
                - Name: GenericLFI_URIPATH
                - Name: GenericRFI_BODY
                - Name: GenericRFI_QUERYARGUMENTS
                - Name: GenericRFI_URIPATH
                - Name: NoUserAgent_HEADER
                - Name: RestrictedExtensions_QUERYARGUMENTS
                - Name: RestrictedExtensions_URIPATH
                - Name: SizeRestrictions_BODY
                - Name: SizeRestrictions_Cookie_HEADER
                - Name: SizeRestrictions_QUERYSTRING
                - Name: SizeRestrictions_URIPATH
                - Name: UserAgent_BadBots_HEADER
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-aws-crs-metric'

        - Name: Bad-Inputs
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules:
                - Name: ExploitablePaths_URIPATH
                - Name: Host_localhost_HEADER
                - Name: JavaDeserializationRCE_BODY
                - Name: JavaDeserializationRCE_HEADER
                - Name: JavaDeserializationRCE_QUERYSTRING
                - Name: JavaDeserializationRCE_URIPATH
                # - Name: Log4JRCE
                - Name: PROPFIND_METHOD
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-bad-inputs-metric'

        - Name: Anonymous-IpList
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
              ExcludedRules:
                - Name: AnonymousIPList
                - Name: HostingProviderIPList
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-anonymous-iplist-metric'

        - Name: SQLInject-RuleSet
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
              ExcludedRules:
                - Name: SQLiExtendedPatterns_QUERYARGUMENTS
                - Name: SQLi_BODY
                - Name: SQLi_COOKIE
                - Name: SQLi_QUERYARGUMENTS
                - Name: SQLi_URIPATH
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AWS::StackName}-${Environment}-SQLinjection-ruleset-metric'

        - Name: RateBased-CountIpRule
          Priority: 4
          Statement:
            RateBasedStatement:
              Limit: 100
              AggregateKeyType: IP
          Action:
            Count: { }
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub "${AWS::StackName}-${Environment}-RateBased-CountIp-ruleset-metric"
            SampledRequestsEnabled: true

      Scope: REGIONAL
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${Environment}'
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AWS::StackName}-${Environment}-metric'

  cloudwatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub 'aws-waf-logs-${AWS::StackName}-${Environment}-cloudWatchLog'
      RetentionInDays: 180
      KmsKeyId:  !If
        - NotDevelopment
        - !GetAtt WAFLoggingKmsKey.Arn
        - !Ref AWS::NoValue

  WebAclLogging:
    Type: 'AWS::WAFv2::LoggingConfiguration'
    Properties:
      ResourceArn: !GetAtt
        - MainWebAcl
        - Arn
      LogDestinationConfigs:
        - !GetAtt cloudwatchLogsGroup.Arn
      LoggingFilter:
        DefaultBehavior: KEEP
        Filters:
          - Behavior: KEEP
            Conditions:
              - ActionCondition:
                  Action: BLOCK
              - ActionCondition:
                  Action: COUNT
            Requirement: MEETS_ANY
      RedactedFields:
        - SingleHeader:
            Name: password

  WAFLoggingKmsKey:
    Type: AWS::KMS::Key
    Condition: NotDevelopment
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

Outputs:
  MainWebAclArn:
    Description: Self-service Main WAF Web ACL
    Value: !GetAtt MainWebAcl.Arn
    Export:
      Name: MainWebAclArn