AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment pipelines for the Admin Tool

Parameters:
  # Template reference https://github.com/alphagov/di-devplatform-deploy
  TemplateStorageBucket:
    Type: String
    Default: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com
  ExportNamePrefix:
    Type: String
    Default: secure-pipelines
    AllowedPattern: ^.*[^-]$
    Description: Prefix to use when importing or exporting values
  StackNamePrefix:
    Type: String
    Default: self-service
    AllowedPattern: ^.*[^-]$
    MaxLength: 14
    Description: Prefix applied to the deployed application stack names
  Environment:
    Type: String
  NextAccount:
    Type: String
    Default: ""
  GitHubRepositoryName:
    Type: String
    Default: di-onboarding-self-service-experience
  SigningProfileARN:
    Type: String
  SigningProfileVersionARN:
    Type: String
  ContainerSigningKeyARN:
    Type: String
    Default: none
  APISourceBucketARN:
    Type: String
    Default: none
  CognitoSourceBucketARN:
    Type: String
    Default: none
  DynamoDBSourceBucketARN:
    Type: String
    Default: none
  FrontendSourceBucketARN:
    Type: String
    Default: none

Conditions:
  IsFinalAccount: !Not [ !Condition PromotionEnabled ]
  PromotionEnabled: !Not [ !Equals [ !Ref NextAccount, "" ] ]
  APIRepositorySource: !Equals [ !Ref APISourceBucketARN, "none" ]
  CognitoRepositorySource: !Equals [ !Ref CognitoSourceBucketARN, "none" ]
  DynamoDBRepositorySource: !Equals [ !Ref DynamoDBSourceBucketARN, "none" ]
  FrontendRepositorySource: !Equals [ !Ref FrontendSourceBucketARN, "none" ]

Resources:
  APIDeployer:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDBDeployer
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Backend
        - Key: sse:deployment-source
          Value: secure-pipelines
      Parameters:
        Environment: !Ref Environment
        SAMStackName: !Sub ${StackNamePrefix}-api
        TruncatedPipelineStackName: !Sub ${StackNamePrefix}-api
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        SigningProfileArn: !Ref SigningProfileARN
        # TODO confirm the API stacks needs this param
        VpcStackName: !ImportValue VPC-StackName
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !If [ IsFinalAccount, All, Failures ]
        ArtifactSourceBucketArn: !Ref APISourceBucketARN
        GitHubRepositoryName: !If [ APIRepositorySource, !Ref GitHubRepositoryName, "none" ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        PipelineEnvironmentNameEnabled: "Yes"
        AllowedServiceOne: Lambda
        AllowedServiceTwo: DynamoDB
        AllowedServiceThree: SNS
        AllowedServiceFour: StepFunctions
        AllowedServiceFive: EC2
         AllowedServiceSix: SQS

  CognitoDeployer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Authentication
        - Key: sse:deployment-source
          Value: secure-pipelines
      Parameters:
        Environment: !Ref Environment
        SAMStackName: !Sub ${StackNamePrefix}-cognito
        TruncatedPipelineStackName: !Sub ${StackNamePrefix}-cognito
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        SigningProfileArn: !Ref SigningProfileARN
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !If [ IsFinalAccount, All, Failures ]
        ArtifactSourceBucketArn: !Ref CognitoSourceBucketARN
        GitHubRepositoryName: !If [ CognitoRepositorySource, !Ref GitHubRepositoryName, "none" ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        PipelineEnvironmentNameEnabled: "Yes"
        AllowedServiceOne: Cognito
        AllowedServiceTwo: Lambda
        AllowedServiceThree: SNS
        AllowedServiceFour: EC2

  DynamoDBDeployer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Database
        - Key: sse:deployment-source
          Value: secure-pipelines
      Parameters:
        Environment: !Ref Environment
        SAMStackName: !Sub ${StackNamePrefix}-dynamodb
        TruncatedPipelineStackName: !Sub ${StackNamePrefix}-dynamodb
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        SigningProfileArn: !Ref SigningProfileARN
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !If [ IsFinalAccount, All, Failures ]
        ArtifactSourceBucketArn: !Ref DynamoDBSourceBucketARN
        GitHubRepositoryName: !If [ DynamoDBRepositorySource, !Ref GitHubRepositoryName, "none" ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        PipelineEnvironmentNameEnabled: "Yes"
        AllowedServiceOne: DynamoDB

  FrontendDeployer:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDBDeployer
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Frontend
        - Key: sse:deployment-source
          Value: secure-pipelines
      Parameters:
        Environment: !Ref Environment
        SAMStackName: !Sub ${StackNamePrefix}-frontend
        TruncatedPipelineStackName: !Sub ${StackNamePrefix}-frontend
        ContainerSignerKmsKeyArn: !Ref ContainerSigningKeyARN
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        SigningProfileArn: !Ref SigningProfileARN
        VpcStackName: !ImportValue VPC-StackName
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !If [ IsFinalAccount, All, Failures ]
        ArtifactSourceBucketArn: !Ref FrontendSourceBucketARN
        GitHubRepositoryName: !If [ FrontendRepositorySource, !Ref GitHubRepositoryName, "none" ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        PipelineEnvironmentNameEnabled: "Yes"
        AllowedServiceOne: ECR & ECS
        AllowedServiceTwo: Cognito
        AllowedServiceThree: DynamoDB

  FrontendECRRepository:
    Type: AWS::CloudFormation::Stack
    Condition: FrontendRepositorySource
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/container-image-repository/template.yaml
      Parameters:
        PipelineStackName: !Select [ 1, !Split [ "/", !Ref FrontendDeployer ] ]

  APIDeploymentPolicy:
    Type: AWS::IAM::Policy
    Condition: APIRepositorySource
    Properties:
      Roles: [ !GetAtt APIDeployer.Outputs.GitHubActionsRoleName ]
      PolicyName: !Sub ${StackNamePrefix}-api-deployment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:ListPipelineExecutions
              - codepipeline:StartPipelineExecution
            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${APIDeployer.Outputs.PipelineName}
          - Effect: Allow
            Action:
              - codepipeline:EnableStageTransition
              - codepipeline:DisableStageTransition
            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${APIDeployer.Outputs.PipelineName}/Deploy

  CognitoDeploymentPolicy:
    Type: AWS::IAM::Policy
    Condition: CognitoRepositorySource
    Properties:
      Roles: [ !GetAtt CognitoDeployer.Outputs.GitHubActionsRoleName ]
      PolicyName: !Sub ${StackNamePrefix}-cognito-deployment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:ListPipelineExecutions
              - codepipeline:StartPipelineExecution
            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CognitoDeployer.Outputs.PipelineName}
          - Effect: Allow
            Action:
              - codepipeline:EnableStageTransition
              - codepipeline:DisableStageTransition
            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CognitoDeployer.Outputs.PipelineName}/Deploy

  DynamoDBDeploymentPolicy:
    Type: AWS::IAM::Policy
    Condition: DynamoDBRepositorySource
    Properties:
      Roles: [ !GetAtt DynamoDBDeployer.Outputs.GitHubActionsRoleName ]
      PolicyName: !Sub ${StackNamePrefix}-dynamodb-deployment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action:
            - codepipeline:ListPipelineExecutions
            - codepipeline:StartPipelineExecution
          Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${DynamoDBDeployer.Outputs.PipelineName}

  FrontendDeploymentPolicy:
    Type: AWS::IAM::Policy
    Condition: FrontendRepositorySource
    Properties:
      Roles: [ !GetAtt FrontendDeployer.Outputs.GitHubActionsRoleName ]
      PolicyName: !Sub ${StackNamePrefix}-frontend-deployment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codepipeline:ListPipelineExecutions
              - codepipeline:StartPipelineExecution
            Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${FrontendDeployer.Outputs.PipelineName}
          - Effect: Allow
            Action: ecr:BatchDeleteImage
            Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${FrontendECRRepository.Outputs.ContainerRepositoryName}

Outputs:
  # Promotion
  APIPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt APIDeployer.Outputs.ArtifactPromotionBucketArn
  CognitoPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt CognitoDeployer.Outputs.ArtifactPromotionBucketArn
  DynamoDBPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt DynamoDBDeployer.Outputs.ArtifactPromotionBucketArn
  FrontendPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt FrontendDeployer.Outputs.ArtifactPromotionBucketArn

  # Deployment
  APIDeploymentRoleArn:
    Condition: APIRepositorySource
    Value: !GetAtt APIDeployer.Outputs.GitHubActionsRoleArn
  APIArtifactSourceBucketName:
    Condition: APIRepositorySource
    Value: !GetAtt APIDeployer.Outputs.GitHubArtifactSourceBucketName
  APIPipelineName:
    Value: !GetAtt APIDeployer.Outputs.PipelineName
  CognitoDeploymentRoleArn:
    Condition: CognitoRepositorySource
    Value: !GetAtt CognitoDeployer.Outputs.GitHubActionsRoleArn
  CognitoArtifactSourceBucketName:
    Condition: CognitoRepositorySource
    Value: !GetAtt CognitoDeployer.Outputs.GitHubArtifactSourceBucketName
  CognitoPipelineName:
    Value: !GetAtt CognitoDeployer.Outputs.PipelineName
  DynamoDBDeploymentRoleArn:
    Condition: DynamoDBRepositorySource
    Value: !GetAtt DynamoDBDeployer.Outputs.GitHubActionsRoleArn
  DynamoDBArtifactSourceBucketName:
    Condition: DynamoDBRepositorySource
    Value: !GetAtt DynamoDBDeployer.Outputs.GitHubArtifactSourceBucketName
  DynamoDBPipelineName:
    Value: !GetAtt DynamoDBDeployer.Outputs.PipelineName
  FrontendDeploymentRoleArn:
    Condition: FrontendRepositorySource
    Value: !GetAtt FrontendDeployer.Outputs.GitHubActionsRoleArn
  FrontendArtifactSourceBucketName:
    Condition: FrontendRepositorySource
    Value: !GetAtt FrontendDeployer.Outputs.GitHubArtifactSourceBucketName
  FrontendECRRepositoryName:
    Condition: FrontendRepositorySource
    Value: !GetAtt FrontendECRRepository.Outputs.ContainerRepositoryName
  FrontendPipelineName:
    Value: !GetAtt FrontendDeployer.Outputs.PipelineName
