AWSTemplateFormatVersion: "2010-09-09"
Description: Deployment pipelines for the Admin Tool

Parameters:
  # Template reference https://github.com/alphagov/di-devplatform-deploy
  TemplateStorageBucket:
    Type: String
    Default: https://template-storage-templatebucket-1upzyw6v9cs42.s3.amazonaws.com
  ExportNamePrefix:
    Type: String
    Default: secure-pipelines
    AllowedPattern: ^.*[^-]$
    Description: Prefix to use when importing or exporting values
  Environment:
    Type: String
  NextAccount:
    Type: String
    Default: ""
  GitHubRepositoryName:
    Type: String
    Default: di-onboarding-self-service-experience
  SigningProfileARN:
    Type: String
  SigningProfileVersionARN:
    Type: String
  ContainerSigningKeyARN:
    Type: String
  SlackNotificationType:
    Type: String
    Default: Failures
  APISourceBucketARN:
    Type: String
    Default: none
  CognitoSourceBucketARN:
    Type: String
    Default: none
  DynamoDBSourceBucketARN:
    Type: String
    Default: none
  FrontendSourceBucketARN:
    Type: String
    Default: none

Conditions:
  PromotionEnabled: !Not [ !Equals [ !Ref NextAccount, "" ] ]
  APISourceBucket: !Not [ !Equals [ !Ref APISourceBucketARN, "none" ] ]
  CognitoSourceBucket: !Not [ !Equals [ !Ref CognitoSourceBucketARN, "none" ] ]
  DynamoDBSourceBucket: !Not [ !Equals [ !Ref DynamoDBSourceBucketARN, "none" ] ]
  FrontendSourceBucket: !Not [ !Equals [ !Ref FrontendSourceBucketARN, "none" ] ]

Resources:
  API:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDB
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Backend
      Parameters:
        Environment: !Ref Environment
        SAMStackName: self-service-api
        SigningProfileArn: !Ref SigningProfileARN
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        # TODO confirm the API stacks needs this param
        VpcStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-VPCStackName
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !Ref SlackNotificationType
        ArtifactSourceBucketArn: !Ref APISourceBucketARN
        GitHubRepositoryName: !If [ APISourceBucket, "none", !Ref GitHubRepositoryName ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        AllowedServiceOne: Lambda
        AllowedServiceTwo: DynamoDB
        AllowedServiceThree: SNS
        AllowedServiceFour: StepFunctions

  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Authentication
      Parameters:
        Environment: !Ref Environment
        SAMStackName: self-service-cognito
        SigningProfileArn: !Ref SigningProfileARN
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !Ref SlackNotificationType
        ArtifactSourceBucketArn: !Ref CognitoSourceBucketARN
        GitHubRepositoryName: !If [ CognitoSourceBucket, "none", !Ref GitHubRepositoryName ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        AllowedServiceOne: Cognito
        AllowedServiceTwo: Lambda
        AllowedServiceThree: SNS

  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Database
      Parameters:
        Environment: !Ref Environment
        SAMStackName: self-service-dynamo-db
        SigningProfileArn: !Ref SigningProfileARN
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !Ref SlackNotificationType
        ArtifactSourceBucketArn: !Ref DynamoDBSourceBucketARN
        GitHubRepositoryName: !If [ DynamoDBSourceBucket, "none", !Ref GitHubRepositoryName ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        AllowedServiceOne: DynamoDB

  Frontend:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateStorageBucket}/sam-deploy-pipeline/template.yaml
      Tags:
        - Key: System
          Value: Self-Service
        - Key: Service
          Value: Frontend
      Parameters:
        Environment: !Ref Environment
        SAMStackName: self-service-frontend
        SigningProfileArn: !Ref SigningProfileARN
        SigningProfileVersionArn: !Ref SigningProfileVersionARN
        ContainerSignerKmsKeyArn: !Ref ContainerSigningKeyARN
        VpcStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-VPCStackName
        BuildNotificationStackName:
          Fn::ImportValue: !Sub ${ExportNamePrefix}-SlackNotificationsStackName
        SlackNotificationType: !Ref SlackNotificationType
        ArtifactSourceBucketArn: !Ref FrontendSourceBucketARN
        GitHubRepositoryName: !If [ FrontendSourceBucket, "none", !Ref GitHubRepositoryName ]
        AllowedAccounts: !Ref NextAccount
        IncludePromotion: !If [ PromotionEnabled, "Yes", "No" ]
        AccessLogsCustomBucketNameEnabled: "No"
        ProgrammaticPermissionsBoundary: "True"
        AllowedServiceOne: ECR & ECS

Outputs:
  APIPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt API.Outputs.ArtifactPromotionBucketArn
  CognitoPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt Cognito.Outputs.ArtifactPromotionBucketArn
  DynamoDBPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt DynamoDB.Outputs.ArtifactPromotionBucketArn
  FrontendPromotionBucket:
    Condition: PromotionEnabled
    Value: !GetAtt Frontend.Outputs.ArtifactPromotionBucketArn
