AWSTemplateFormatVersion: 2010-09-09
Description: >-
  DynaomDB table for di-onboarding-self-service-experience
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  Table:
    # checkov:skip=CKV_AWS_28: "Ensure Dynamodb point in time recovery (backup) is enabled"
    # checkov:skip=CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK"
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      AttributeDefinitions:
        -
          AttributeName: pk
          AttributeType: S
        -
          AttributeName: sk
          AttributeType: S
      KeySchema:
        -
          AttributeName: pk
          KeyType: HASH
        -
          AttributeName: sk
          KeyType: RANGE

      BillingMode: PAY_PER_REQUEST

      GlobalSecondaryIndexes:
        -
          IndexName: gsi1
          KeySchema:
            -
              AttributeName: sk
              KeyType: HASH
            -
              AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  Sessions:
    # checkov:skip=CKV_AWS_28: "Ensure Dynamodb point in time recovery (backup) is enabled"
    # checkov:skip=CKV_AWS_119: "Ensure DynamoDB Tables are encrypted using a KMS Customer Managed CMK"
    Type: AWS::DynamoDB::Table
    Properties:
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: TableName generated for this stack
    Value: !Ref Table
    Export:
      Name: AdminToolDataTable
  SessionsTableName:
    Description: Sessions table name for session storage
    Value: !Ref Sessions
    Export:
      Name: AdminToolSessionsTable
