AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DNS configuration for self-service development and preview sub domains deployed in the development account

Conditions:
  IsDevelopmentAccount: !Equals [ !Ref AWS::AccountId, 494650018671 ]

Resources:
  SignInServiceDevelopmentHostedZone:
    Type: AWS::Route53::HostedZone
    Condition: IsDevelopmentAccount
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: Hosted zone for sign-in.service.gov.uk development sub-domain
      Name: development.sign-in.service.gov.uk.

  SignInServicePreviewHostedZone:
    Type: AWS::Route53::HostedZone
    Condition: IsDevelopmentAccount
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: Hosted zone for sign-in.service.gov.uk preview sub-domain
      Name: preview.sign-in.service.gov.uk.

Outputs:
  DevelopmentHostedZone:
    Condition: IsDevelopmentAccount
    Description: Hosted Zone for sign-in.service.gov.uk development sub-domain
    Value: !Ref SignInServiceDevelopmentHostedZone
    Export:
      Name: SignInServiceDevelopmentHostedZone

  PreviewHostedZone:
    Condition: IsDevelopmentAccount
    Description: Hosted Zone for sign-in.service.gov.uk preview sub-domain
    Value: !Ref SignInServicePreviewHostedZone
    Export:
      Name: SignInServicePreviewHostedZone
