AWSTemplateFormatVersion: "2010-09-09"
Description: DNS configuration for the self-service staging domains deployed in the staging account

Conditions:
  IsStagingAccount: !Equals [ !Ref AWS::AccountId, 325730373996 ]

Resources:
  SignInServiceStagingHostedZone:
    Type: AWS::Route53::HostedZone
    Condition: IsStagingAccount
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: Hosted zone for sign-in.service.gov.uk staging sub-domain
      Name: staging.sign-in.service.gov.uk.

Outputs:
  StagingHostedZone:
    Condition: IsStagingAccount
    Description: Hosted Zone for sign-in.service.gov.uk staging sub-domain
    Value: !Ref SignInServiceStagingHostedZone
    Export:
      Name: SignInServiceStagingHostedZone
