AWSTemplateFormatVersion: "2010-09-09"
Description: Config to enable Control Tower in self-service AWS accounts

Resources:
  ControlTowerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSControlTowerExecution
      ManagedPolicyArns: [ arn:aws:iam::aws:policy/AdministratorAccess ]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: arn:aws:iam::892537467220:root
