name: Build a SAM application
description: Build a backend component and optionally upload a GitHub Actions artifact
inputs:
  name:
    description: "The name of the component to build"
    required: true
  template:
    description: "Path of the SAM template file to use"
    required: false
  manifest:
    description: "Path to a custom dependency manifest file"
    required: false
  source-dir:
    description: "Source code directory to use as a cache key when building the SAM application"
    required: false
  base-dir:
    description: "The SAM base directory to use when building the application"
    required: false
  additional-artifact-paths:
    description: "Additional paths to include in the artifact in addition to the built SAM application"
    required: false
outputs:
  component:
    description: "Pass through the component name"
    value: ${{ inputs.name }}
  artifact-name:
    description: "The name of the uploaded artifact"
    value: ${{ steps.build.outputs.artifact-name }}
runs:
  using: composite
  steps:
    - name: Build SAM application
      continue-on-error: true
      uses: govuk-one-login/github-actions/sam/build-application@6144f39407b01c9b25b39537b3956deca9e32620 # 22/02/2024
      id: build
      with:
        template: ${{ inputs.template }}
        manifest: ${{ inputs.manifest }}
        base-dir: ${{ inputs.base-dir }}
        cache-name: ${{ inputs.name }}
        artifact-name: ${{ inputs.name }}-SAM
        additional-artifact-paths: ${{ inputs.additional-artifact-paths }}
        pull-repository: true