name: "Build and push application"
description: "Build the container and push the application through secure pipelines"
inputs:
  artifact-bucket-name:
    description: "The source bucket to push the deployment artifacts to"
    required: true
  container-repository-name:
    description: "The container repository to push the application image to"
    required: true
  deployment-role-arn:
    description: "The github actions role that is authorized to deploy the applications"
    required: true
  dynatrace-pass-token:
    description: "The dynatrace paas token to download the OneAgent image"
    required: true
  pipeline-name:
    description: "The secure delivery pipeline that pushes this deployment"
    required: true
  test-container-repository-name:
    description: "The container repository to push the tests image to"
    required: true
outputs:
  pipeline-url:
    description: "The url the secure pipeline that deploys the application."
    value: ${{ steps.deploy-application.outputs.pipeline-url }}
runs:
  using: composite
  steps:
    - name: Push test image
      id: push-tests-image
      uses: govuk-one-login/github-actions/aws/ecr/build-docker-image@7e9f6ee1a1f7b30ca9cba4d3893d3ee6313decef # 9/07/2024
      with:
        aws-role-arn: ${{ inputs.deployment-role-arn }}
        repository: ${{ inputs.test-container-repository-name }}
        dockerfile: ui-automation-tests/tests.Dockerfile
        build-path: ui-automation-tests
        image-tags: latest
        immutable-tags: false
        image-version: ${{ github.sha }}

    - name: Login to GDS Dev Dynatrace Container Registry
      uses: docker/login-action@v3
      with:
        registry: khw46367.live.dynatrace.com
        username: khw46367
        password: ${{ inputs.dynatrace-pass-token }}

    - name: Deploy application
      id: deploy-application
      uses: govuk-one-login/github-actions/secure-pipelines/deploy-fargate@c8eefadf581d2087ce2af48b7060c1329cfa5251 # 09/07/2025
      with:
        aws-role-arn: ${{ inputs.deployment-role-arn }}
        artifact-bucket-name: ${{ inputs.artifact-bucket-name }}
        ecr-repository: ${{ inputs.container-repository-name }}
        pipeline-name: ${{ inputs.pipeline-name }}
        dockerfile: infrastructure/frontend/Dockerfile
        template: infrastructure/frontend/frontend.template.yml
