name: Run Pii scan on all cloudformation templates
description: Scans cloudformation templates for correctly configured logging data protection filters
inputs:
  template-format:
    description: "The template format to match, wildcards accepted"
    required: false
    default: "*template*.yml"
  ignore-file:
    description: "Templates files to be ignored by the scan"
    required: true
  ignore-lines:
    description: "Lines that should be skipped in any given template file"
    required: true
runs:
  using: composite
  steps:
    - name: Check if merge commit
      id: check-merge-commit
      shell: bash
      env:
        EVENT: ${{ github.event_name }}
      run: |
        merging=false
        [[ $EVENT == pull_request ]] && merging=true && fetch_depth=2
        echo "fetch-depth=${fetch_depth:-}" >> "$GITHUB_OUTPUT"
        echo "merging=$merging" >> "$GITHUB_OUTPUT"

    - name: Pull repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ steps.check-merge-commit.outputs.fetch-depth }}

    - name: Run Cloudformation Pii Scan
      id: run-pii-scan
      shell: bash
      env:
        TEMPLATE_FORMAT: ${{ inputs.template-format }}
        IGNORE_FILE: ${{ inputs.ignore-file }}
        IGNORE_LINES: ${{ inputs.ignore-lines }}
      run: |
        ./infrastructure/dev/pii_scan.sh -p $TEMPLATE_FORMAT -i $IGNORE_FILE -s $IGNORE_LINES
        exit $?
