AWSTemplateFormatVersion: "2010-09-09"
Description: Admin Tool VPC and networking components to provide security controls and public access to the app
Transform: AWS::LanguageExtensions

Resources:
  CloudWatchLogsResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: DeploymentStacksLogDelivery
      PolicyDocument:
        Fn::ToJsonString:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/onboarding-self-service/* # Application prefix for audit log groups
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/onboarding-product-pages/* # Application prefix for audit log groups
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/onboarding-self-service/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/stepfunction/onboarding-self-service/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/api-gateway/onboarding-self-service/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/cognito/onboarding-self-service/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ecs/onboarding-self-service/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ecs/onboarding-product-pages/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:aws-waf-logs-onboarding-self-service-*:log-stream:*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:aws-waf-logs-onboarding-product-pages-*:log-stream:*
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Principal:
              Service: delivery.logs.amazonaws.com
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
