name: Build API SAM application

on:
  workflow_call:
    outputs:
      component:
        value: ${{ jobs.build.outputs.component }}
      artifact-name:
        value: ${{ jobs.build.outputs.artifact-name }}

concurrency:
  group: build-api-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.build.outputs.component }}
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Build SAM application
        uses: ./.github/actions/build-backend-component
        id: build
        continue-on-error: true
        with:
          name: API
          base-dir: ${{ github.workspace }}
          template: backend/api/api.template.yml
          additional-artifact-paths: backend/api/state-machines

      - name: Debug workspace directory
        if: steps.build.outcome != 'success'
        run: |
          sudo df -h