name: Build Cognito SAM application

on:
  workflow_call:
    outputs:
      component:
        value: ${{ jobs.build.outputs.component }}
      artifact-name:
        value: ${{ jobs.build.outputs.artifact-name }}

concurrency:
  group: build-cognito-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.build.outputs.component }}
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Build SAM application
        uses: ./.github/actions/build-backend-component
        id: build
        with:
          name: cognito
          base-dir: ${{ github.workspace }}
          template: backend/cognito/cognito.template.yml
          manifest: backend/cognito/package.json
          source-dir: backend/cognito
