name: Build frontend stack

on:
  workflow_call:
    inputs:
      image_uri: { required: true, type: string }
      template: { required: false, type: string }
      artifact-name: { required: false, type: string, default: Frontend-SAM }
    outputs:
      template:
        value: ${{ jobs.build.outputs.template }}
      artifact-name:
        value: ${{ inputs.artifact-name }}

concurrency:
  group: build-frontend-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: Build stack
    runs-on: ubuntu-latest
    outputs:
      template: ${{ steps.replace-placeholders.outputs.template }}

    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Replace placeholders
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: replace-placeholders
        env:
          TEMPLATE_FILE: ${{ inputs.template }}
          IMAGE_URI: ${{ inputs.image_uri }}
        run: |
          sam build ${TEMPLATE_FILE:+--template $TEMPLATE_FILE}
          echo "template=.aws-sam/build/template.yaml" >> "$GITHUB_OUTPUT"
          
          if grep -q "CONTAINER-IMAGE-PLACEHOLDER" .aws-sam/build/template.yaml; then
            echo "Replacing \"CONTAINER-IMAGE-PLACEHOLDER\" with new ECR image ref"
            sed -i "s|CONTAINER-IMAGE-PLACEHOLDER|$IMAGE_URI|" .aws-sam/build/template.yaml
          else
            echo "WARNING!!! Image placeholder text \"CONTAINER-IMAGE-PLACEHOLDER\" not found - uploading template anyway"
          fi

      - name: Archive distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          retention-days: 7
          path: .aws-sam/build
