name: Build API SAM application

on:
  workflow_call:
    outputs:
      artifact-name:
        value: ${{ jobs.build.outputs.artifact-name }}

concurrency:
  group: build-api-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    name: API
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - uses: alphagov/di-github-actions/sam/build-application@f1aa97d64bf1be3a6226e0319c597bf4b28c19c8
        id: build
        with:
          additional-artifact-paths: backend/api/state-machines
          template: backend/api/api.template.yml
          base-dir: ${{ github.workspace }}
          artifact-name: api-sam
          cache-key: api
