name: Build API lambdas

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
    secrets:
      aws-role-arn: { required: true }

concurrency:
  group: build-api-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Self-service API
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Cache SAM dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-sam-${{ hashFiles('**/package-lock.json', 'infrastructure/api/*api*.yml') }}
          restore-keys: ${{ runner.os }}-sam-
          path: |
            .aws-sam
            !.aws-sam/build

      - name: Build self-service API
        uses: alphagov/di-github-actions/sam/build-application@f9d4fd5fb5f5a92151bc522925fe2ba7cb1c05fc
        with:
          aws-role-arn: ${{ secrets.aws-role-arn }}
          sam-template-file: infrastructure/api/sse-api.yml
          base-dir: ${{ github.workspace }}

      - name: Archive SAM distribution artifact
        uses: actions/upload-artifact@v3
        with:
          name: self-service-api
          retention-days: 3
          path: |
            .aws-sam/build
            infrastructure/api/state-machines
