name: Clean up deployments
run-name: Delete stale deployments

on:
  workflow_dispatch:
  schedule:
    # Every weekday at 10am
    - cron: '0 10 * * 1-5'

permissions: read-all

jobs:
  delete-fargate-deployments:
    name: Clean up Fargate deployments
    runs-on: ubuntu-latest
    environment: development
    concurrency: deploy-fargate-development-${{ github.head_ref || github.ref_name }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deregister stale task definitions
        uses: govuk-one-login/github-actions/aws/ecs/deregister-stale-task-definitions@94bfee8a40ab914626a7fb5bc459dd2c6a4ed435 # 5/03/2024
        with:
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          family: self-service-frontend
          container: self-service-frontend
