name: Deploy secure pipelines preview
run-name: Upload to AWS [${{ github.head_ref || github.ref_name }}]

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    name: AWS
    uses: ./.github/workflows/upload-to-secure-pipelines.yml
    with:
      environment: development-secure-pipelines
