name: Deploy secure pipelines preview
run-name: Upload to AWS [${{ github.head_ref || github.ref_name }}]

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dynamodb:
    name: Deploy
    uses: ./.github/workflows/upload-dynamodb-package.yml
    with:
      environment: development-secure-pipelines

  build-api:
    name: Build
    uses: ./.github/workflows/build-api.yml

  deploy-api:
    name: Deploy
    needs: [ build-api, deploy-dynamodb ]
    uses: ./.github/workflows/upload-api-package.yml
    with:
      environment: development-secure-pipelines
      artifact-name: ${{ needs.build-api.outputs.artifact-name }}

  build-cognito:
    name: Build
    uses: ./.github/workflows/build-cognito.yml

  deploy-cognito:
    name: Deploy
    needs: build-cognito
    uses: ./.github/workflows/upload-cognito-package.yml
    with:
      environment: development-secure-pipelines
      artifact-name: ${{ needs.build-cognito.outputs.artifact-name }}
