name: Deploy branch with secure pipelines
run-name: Upload to AWS [${{ github.head_ref || github.ref_name }}]

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    name: Upload
    uses: ./.github/workflows/upload-to-secure-pipelines.yml
    with:
      environment: development-secure-pipelines
