name: Preview [secure pipelines]
run-name: Upload to AWS [${{ github.head_ref || github.ref_name }}]

on:
  workflow_dispatch:
  # pull_request:

concurrency:
  group: deploy-secure-pipelines-development
  cancel-in-progress: ${{ github.event_name == 'workflow_dispatch' && true || false }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dynamodb:
    name: DynamoDB
    uses: ./.github/workflows/upload-dynamodb-package.yml
    with:
      environment: development-secure-pipelines

  build-api:
    name: API
    uses: ./.github/workflows/build-api.yml

  deploy-api:
    name: API
    needs: [ build-api, deploy-dynamodb ]
    uses: ./.github/workflows/upload-api-package.yml
    with:
      environment: development-secure-pipelines
      artifact-name: ${{ needs.build-api.outputs.artifact-name }}

  build-cognito:
    name: Cognito
    uses: ./.github/workflows/build-cognito.yml

  deploy-cognito:
    name: Cognito
    needs: [ build-cognito, deploy-dynamodb ]
    uses: ./.github/workflows/upload-cognito-package.yml
    with:
      environment: development-secure-pipelines
      artifact-name: ${{ needs.build-cognito.outputs.artifact-name }}

  build-frontend:
    name: Frontend
    if: ${{ inputs.frontend-artifact == null }}
    uses: ./.github/workflows/build-frontend.yml

  deploy-frontend:
    name: Frontend
    needs: [ build-frontend, deploy-cognito, deploy-dynamodb, deploy-api ]
    uses: ./.github/workflows/upload-frontend-package.yml
    with:
      environment: development-secure-pipelines
      artifact-name: ${{ needs.build-frontend.outputs.artifact-name || inputs.frontend-artifact }}
