name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  build-frontend:
    name: Build
    uses: ./.github/workflows/build-frontend.yml

  run-unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml

  deploy-test-frontend:
    name: Test
    needs: [ build-frontend, run-unit-tests ]
    uses: ./.github/workflows/deploy-to-paas.yml
    with:
      environment: test
      show-test-banner: true
      cf-space-name: self-service-test
      cognito-client: StubCognitoClient
      lambda-facade: StubLambdaFacade
      artifact-name: ${{ needs.build-5-frontend.outputs.artifact-name }}
      url: https://di-self-service-test.london.cloudapps.digital
    secrets:
      cf-username: ${{ secrets.CF_USERNAME }}
      cf-password: ${{ secrets.CF_PASSWORD }}

  run-acceptance-tests:
    name: Run tests
    needs: deploy-test-frontend
    uses: ./.github/workflows/run-acceptance-tests.yml
    with:
      host: ${{ needs.deploy-test-frontend.outputs.deployment-url }}
      environment: ${{ needs.deploy-test-frontend.outputs.environment }}
