name: Acceptance tests

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }

permissions: { }
concurrency: acceptance-test-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  run-acceptance-tests:
    name: Acceptance
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: ui-automation-tests }

    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Node dependencies
        run: |
          npm ci --include-workspace-root
          cd ../express && npm install && cd .. && npm run build-express

      - name: Run cucumber tests
        id: run-tests
        shell: bash
        timeout-minutes: 10
        env:
          REPORT: ${{ runner.temp }}/acceptance-tests.report
          HOST: http://localhost:3000
          STUB_API: true
          TEST_BANNER: true
          NODE_OPTIONS: --max-old-space-size=2048
        run: |
          cd .. && npm run --silent local &
          while ! curl --output /dev/null --silent --head --fail $HOST; do sleep 1 && echo -n .; done;
          npm run acceptance-tests
          cat reports/cucumber-report.json >> "$REPORT"

      - name: Report test results
        if: ${{ failure() && steps.run-tests.outcome == 'failure' }}
        uses: govuk-one-login/github-actions/report-step-result/print-file@5dacba941def444d69f02843feaebed79b5fca51
        with:
          title: Acceptance tests
          language: shell
          file-path: ${{ runner.temp }}/acceptance-tests.report
