name: Acceptance tests

on:
  workflow_call:
    inputs:
      host: { required: true, type: string }
      environment: { required: true, type: string }

permissions: read-all
concurrency: deploy-paas-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  run-acceptance-tests:
    name: Acceptance
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: express }

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Install Node dependencies
        run: npm install

      - name: Run cucumber tests
        id: run-tests
        shell: bash
        env:
          HOST: ${{ inputs.host }}
          REPORT: ${{ runner.temp }}/acceptance-tests.report
        run: |
          features=(features/*.feature)
          
          for feature in "${features[@]}"; do
            [[ ${idx:-} ]] && idx=$((idx + 1)) && echo | tee heading || idx=1
            echo "#--- [$idx/${#features[@]}] ${feature#*/} ---#" | tee -a heading && echo >> heading
            npm run cucumber -- --format summary:results "$feature" || cat heading results >> "$REPORT"
          done
          
          [[ -s $REPORT ]] && exit 1 || exit 0

      - name: Report test results
        if: ${{ failure() && steps.run-tests.outcome == 'failure' }}
        uses: alphagov/di-github-actions/report-step-result/print-file@adca52e1188a4ee53d6c17eeeaefe3a6f8840e59
        with:
          title: Acceptance tests
          language: shell
          file-path: ${{ runner.temp }}/acceptance-tests.report
