name: Sonarcloud

permissions: read-all
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    sonarcloud:
        if: startsWith(github.head_ref, 'dependabot') != true
        name: SonarCloud
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  cache: npm

            - name: Install Node dependencies
              run: npm install

            - name: Generate coverage report
              run: npm run test:cov

            - name: Fix Code Coverage Paths
              working-directory: ./coverage
              run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' lcov.info

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
