name: Deploy DynamoDB through Secure Pipelines

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }

concurrency: deploy-dynamodb-secure-pipelines-${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.pipeline-url }}

    steps:
      - name: Deploy
        id: deploy
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-application@94bfee8a40ab914626a7fb5bc459dd2c6a4ed435 # 5/03/2024
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ vars.DYNAMO_DB_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.DYNAMO_DB_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          pipeline-name: ${{ vars.DYNAMO_DB_PIPELINE_NAME }}
          template: backend/dynamodb/dynamodb.template.yml
