name: Deploy API through Secure Pipelines

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      artifact-name: { required: true, type: string }

concurrency: deploy-api-secure-pipelines-${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.pipeline-url }}

    steps:
      - name: Deploy
        id: deploy
        uses: alphagov/di-github-actions/secure-pipelines/deploy-application@407381405d22479808a226de506ad19ba22fd3f5
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ vars.API_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.API_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          pipeline-name: ${{ vars.API_PIPELINE_NAME }}
          artifact-name: ${{ inputs.artifact-name }}
          template: .aws-sam/build/template.yaml
