name: Deploy Cognito through Secure Pipelines

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      artifact-name: { required: true, type: string }
      cancel-in-progress: { required: false, type: boolean, default: true }

concurrency:
  group: deploy-cognito-secure-pipelines-${{ inputs.environment }}
  cancel-in-progress: ${{ inputs.cancel-in-progress }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Cognito
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.pipeline-url }}

    steps:
      - name: Deploy
        id: deploy
        uses: alphagov/di-github-actions/secure-pipelines/deploy-application@670861e1bb962bffdd45e30ce029be26b862ac36
        timeout-minutes: 15
        with:
          aws-role-arn: ${{ vars.COGNITO_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.COGNITO_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          pipeline-name: ${{ vars.COGNITO_PIPELINE_NAME }}
          artifact-name: ${{ inputs.artifact-name }}
