name: Upload artifacts for deployment with secure pipelines

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }

concurrency: upload-secure-pipelines-${{ inputs.environment }}-${{ github.head_ref || github.ref_name }}

permissions:
  id-token: write
  contents: read

jobs:
  upload-cognito:
    name: Cognito
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Upload Cognito SAM package
        uses: alphagov/di-github-actions/secure-pipelines/upload-sam-package@78978571966007f342dd46b61c8c4d2d5e5da81b
        with:
          template: backend/cognito/cognito.template.yml
          aws-role-arn: ${{ vars.COGNITO_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.COGNITO_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
