name: Upload Frontend to secure pipelines

on:
  workflow_dispatch:
  push:
   branches: [ main ]
   paths: [ express/** ]

permissions: read-all
concurrency: upload-frontend-secure-pipelines-build-${{ github.head_ref || github.ref_name }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-front-app.yml

  deploy:
    name: Upload package
    runs-on: ubuntu-latest
    environment: build
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Pull repository
        uses: actions/checkout@v3

      - name: Get distribution artifact
        uses: actions/download-artifact@v3
        with:
          name: self-service-front

      - name: Upload frontend package
        uses: alphagov/di-devplatform-upload-action-ecr@d1.0.3
        with:
          artifact-bucket-name: ${{ secrets.FRONTEND_BUILD_ARTIFACT_BUCKET_NAME }}
          container-sign-kms-key-arn: ${{ secrets.FRONTEND_CONTAINER_SIGN_KMS_KEY }}
          template-file: infrastructure/ci/dev-platform/frontend-template.yml
          role-to-assume-arn:  ${{ secrets.FRONTEND_BUILD_GHA_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.FRONTEND_BUILD_ECR_REPOSITORY }}
          dockerfile: infrastructure/frontend/Dockerfile
          checkout-repo: false
          
