name: Upload Frontend to secure pipelines

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      artifact-name: { required: true, type: string }
    secrets:
      dynatrace-pass-token: { required: true }

concurrency: deploy-frontend-secure-pipelines-${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.pipeline-url }}

    steps:
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.dynatrace-pass-token }}

      - name: Deploy
        id: deploy
        uses: govuk-one-login/github-actions/secure-pipelines/deploy-fargate@5e4b2d8a5d5e2af09620f1f5cb2c5fd89ec8a257 # 5/03/2024
        timeout-minutes: 20
        with:
          aws-role-arn: ${{ vars.FRONTEND_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.FRONTEND_ARTIFACT_SOURCE_BUCKET_NAME }}
          container-signing-key-arn: ${{ vars.CONTAINER_SIGNING_KEY_ARN }}
          ecr-repository: ${{ vars.FRONTEND_ECR_REPOSITORY_NAME }}
          pipeline-name: ${{ vars.FRONTEND_PIPELINE_NAME }}
          dockerfile: infrastructure/frontend/Dockerfile
          template: infrastructure/frontend/frontend.template.yml
          artifact-name: ${{ inputs.artifact-name }}
          artifact-path: express/dist
