name: Upload Cognito SAM package to S3

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      artifact-name: { required: true, type: string }

concurrency:
  group: upload-cognito-secure-pipelines-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    name: Cognito
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.upload.outputs.pipeline-url }}
    steps:
      - uses: alphagov/di-github-actions/secure-pipelines/upload-sam-package@670861e1bb962bffdd45e30ce029be26b862ac36
        id: upload
        with:
          aws-role-arn: ${{ vars.COGNITO_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.COGNITO_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          pipeline-name: ${{ vars.COGNITO_PIPELINE_NAME }}
          artifact-name: ${{ inputs.artifact-name }}
