name: Deploy secure pipelines preview
run-name: Upload to AWS [${{ github.head_ref || github.ref_name }}]

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment: { required: true, type: string }

concurrency: deploy-secure-pipelines-${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  build-cognito:
    name: Build Cognito
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - uses: alphagov/di-github-actions/sam/build-application@f1aa97d64bf1be3a6226e0319c597bf4b28c19c8
        id: build
        with:
          template: backend/cognito/cognito.template.yml
          artifact-name: cognito-sam
          cache-key: cognito

  upload-cognito:
    name: Upload Cognito
    needs: build-cognito
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: alphagov/di-github-actions/secure-pipelines/upload-sam-package@f1aa97d64bf1be3a6226e0319c597bf4b28c19c8
        with:
          aws-role-arn: ${{ vars.COGNITO_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.COGNITO_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          artifact-name: ${{ needs.build-cognito.outputs.artifact-name }}

  upload-dynamodb:
    name: Upload DynamoDB
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: alphagov/di-github-actions/secure-pipelines/upload-sam-package@f1aa97d64bf1be3a6226e0319c597bf4b28c19c8
        with:
          aws-role-arn: ${{ vars.DYNAMO_DB_DEPLOYMENT_ROLE_ARN }}
          artifact-bucket-name: ${{ vars.DYNAMO_DB_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          template: backend/dynamodb/dynamodb.template.yml
